name: publish

on: 
  push:
    branches:
    - master

jobs:
  run-puppeteer:
    name: Run puppeteer tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Prepare modules
      run: npm install
